"""enhanced_memory_schema_1_10

Revision ID: ad661e3d4391
Revises: a65d7f32c441
Create Date: 2026-05-24 18:57:22.838583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad661e3d4391'
down_revision: Union[str, None] = 'a65d7f32c441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('type_metadata', sa.Text(), nullable=True))
    op.add_column('memories', sa.Column('file_path', sa.String(), nullable=True))
    op.add_column('memories', sa.Column('commit_sha', sa.String(), nullable=True))
    op.add_column('memories', sa.Column('superseded_by', sa.String(), nullable=True))
    op.add_column('memories', sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memories', 'valid_until')
    op.drop_column('memories', 'superseded_by')
    op.drop_column('memories', 'commit_sha')
    op.drop_column('memories', 'file_path')
    op.drop_column('memories', 'type_metadata')
    # ### end Alembic commands ###
