"""
Sub-phase 1.16 Stress Tests — Memory Health Dashboard.

Tests every metric and issue generated by GET /projects/{id}/health:
  1.  Empty project yields zeroed counters with no crash
  2.  Status counts are accurate (active / resolved / stale / archived / superseded)
  3.  Quality buckets bin correctly
  4.  avg_quality_score is the mean of active memories' quality scores
  5.  Review status breakdown counts auto_extracted vs verified
  6.  Traceability percentages are accurate
  7.  Type distribution contains correct counts by memory type
  8.  avg_confidence and low_confidence_count are correct
  9.  Issue: high_unreviewed_count fires when >50% are auto_extracted
  10. Issue: high_unreviewed_count absent when majority are verified
  11. Issue: stale_active_memories fires for memories not updated in 30+ days
  12. Issue: low_avg_quality fires when average quality < 0.40
  13. Issue: low_traceability fires when >60% lack source reference
  14. Issue: rejected_memories_present fires when any memory is rejected
  15. generated_at is present and ISO-format datetime
  16. 404 for non-existent project
  17. Superseded memories appear in superseded_count, not active_count
  18. Resolved memories appear in resolved_count
  19. Quality buckets sum to active_count
  20. Health endpoint does not count superseded memories in quality metrics
"""
import pytest
from fastapi.testclient import TestClient
from sqlalchemy import text
from sqlalchemy.orm import Session
from datetime import datetime, timezone, timedelta

from app import models


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _project(client: TestClient, name: str = "Health Test Project") -> str:
    r = client.post("/projects", json={"name": name})
    assert r.status_code == 201
    return r.json()["id"]


def _mem(
    client: TestClient,
    pid: str,
    *,
    title: str = "Health test memory",
    content: str = "Some content for health testing here.",
    mem_type: str = "decision",
    importance: int = 3,
    confidence: float = 0.80,
    status: str = "active",
    tags: list[str] | None = None,
    file_path: str | None = None,
    symbol_name: str | None = None,
    type_metadata: dict | None = None,
    source_type: str | None = None,
    source_quote: str | None = None,
    review_status: str | None = None,
) -> dict:
    body: dict = {
        "type": mem_type,
        "title": title,
        "content": content,
        "importance": importance,
        "confidence": confidence,
        "status": status,
        "tags": tags or [],
    }
    for k, v in [
        ("file_path", file_path),
        ("symbol_name", symbol_name),
        ("type_metadata", type_metadata),
        ("source_type", source_type),
        ("source_quote", source_quote),
        ("review_status", review_status),
    ]:
        if v is not None:
            body[k] = v
    r = client.post(f"/projects/{pid}/memories", json=body)
    assert r.status_code == 201, r.text
    return r.json()


def _session(client: TestClient, pid: str, content: str) -> str:
    r = client.post(f"/projects/{pid}/sessions", json={
        "tool_name": "Claude",
        "title": "Health Test Session",
        "raw_content": content,
        "session_date": "2026-05-25",
    })
    assert r.status_code == 201
    return r.json()["id"]


def _health(client: TestClient, pid: str) -> dict:
    r = client.get(f"/projects/{pid}/health")
    assert r.status_code == 200, r.text
    return r.json()


# ---------------------------------------------------------------------------
# 1. Empty project
# ---------------------------------------------------------------------------

class TestEmptyProject:
    def test_empty_project_returns_zeroed_report(self, client: TestClient):
        pid = _project(client)
        h = _health(client, pid)
        assert h["total_memories"] == 0
        assert h["active_count"] == 0
        assert h["avg_quality_score"] is None
        assert h["avg_confidence"] is None
        assert h["low_confidence_count"] == 0
        assert h["type_distribution"] == {}

    def test_empty_project_has_no_issues(self, client: TestClient):
        pid = _project(client)
        h = _health(client, pid)
        issue_codes = [i["code"] for i in h["issues"]]
        assert "stale_active_memories" not in issue_codes
        assert "low_avg_quality" not in issue_codes

    def test_empty_project_traceability_zero(self, client: TestClient):
        pid = _project(client)
        h = _health(client, pid)
        assert h["pct_with_session_ref"] == 0.0
        assert h["pct_with_source_quote"] == 0.0
        assert h["pct_with_source_type"] == 0.0


# ---------------------------------------------------------------------------
# 2. Status counts
# ---------------------------------------------------------------------------

class TestStatusCounts:
    def test_active_count_correct(self, client: TestClient):
        pid = _project(client)
        _mem(client, pid, title="Active memory 1")
        _mem(client, pid, title="Active memory 2")
        h = _health(client, pid)
        assert h["active_count"] == 2
        assert h["total_memories"] == 2

    def test_resolved_count_correct(self, client: TestClient):
        pid = _project(client)
        m = _mem(client, pid, title="Resolved memory")
        client.put(f"/memories/{m['id']}", json={"status": "resolved"})
        h = _health(client, pid)
        assert h["resolved_count"] == 1
        assert h["active_count"] == 0

    def test_stale_status_count_correct(self, client: TestClient):
        pid = _project(client)
        m = _mem(client, pid, title="Manually staled")
        client.put(f"/memories/{m['id']}", json={"status": "stale"})
        h = _health(client, pid)
        assert h["stale_count"] == 1
        assert h["active_count"] == 0

    def test_archived_count_correct(self, client: TestClient):
        pid = _project(client)
        m = _mem(client, pid, title="Archived memory")
        client.put(f"/memories/{m['id']}", json={"status": "archived"})
        h = _health(client, pid)
        assert h["archived_count"] == 1

    def test_superseded_count_correct(self, client: TestClient):
        pid = _project(client)
        m = _mem(client, pid, title="Original decision")
        client.post(f"/memories/{m['id']}/supersede", json={
            "type": "decision",
            "title": "Superseding decision with updated approach",
            "content": "The updated decision content replaces the original completely.",
        })
        h = _health(client, pid)
        assert h["superseded_count"] == 1
        # The new memory is active → active_count == 1
        assert h["active_count"] == 1


# ---------------------------------------------------------------------------
# 3 & 4. Quality buckets + avg_quality_score
# ---------------------------------------------------------------------------

class TestQualityMetrics:
    def test_quality_buckets_sum_to_active_count(self, client: TestClient):
        pid = _project(client)
        for i in range(3):
            _mem(client, pid, title=f"Quality bucket test {i}", content="Content for bucketing test.")
        h = _health(client, pid)
        b = h["quality_buckets"]
        bucket_sum = b["excellent"] + b["good"] + b["fair"] + b["poor"]
        assert bucket_sum == h["active_count"]

    def test_rich_memory_lands_in_excellent_bucket(self, client: TestClient):
        pid = _project(client)
        # Enough signals to push quality_score >= 0.75:
        # title(>=50)=+0.20, content(>=200)=+0.15, type_metadata=+0.10, tags=+0.05,
        # source_quote=+0.05, source_type=+0.05, file_path=+0.10, symbol_name=+0.05,
        # related_files=+0.05, confidence=0.8*0.05=+0.04 → ~0.84
        _mem(
            client, pid,
            title="We decided to use FastAPI as the primary backend web framework for this project",
            content=(
                "After thorough evaluation of multiple web frameworks including Flask, Django REST "
                "Framework, and FastAPI, we selected FastAPI because of its native async support, "
                "type safety, and automatic OpenAPI documentation generation. This is a critical "
                "architecture decision that affects every API endpoint we build."
            ),
            tags=["structure"],
            file_path="app/main.py",
            symbol_name="create_app",
            type_metadata={"rationale": "async support", "alternatives_considered": ["Flask", "DRF"]},
            source_type="manual",
            source_quote="We decided to use FastAPI because of performance and type safety.",
        )
        h = _health(client, pid)
        assert h["quality_buckets"]["excellent"] >= 1

    def test_minimal_memory_lands_in_poor_bucket(self, client: TestClient):
        pid = _project(client)
        _mem(client, pid, title="A", content="B" * 5)
        h = _health(client, pid)
        assert h["quality_buckets"]["poor"] >= 1

    def test_avg_quality_score_is_mean(self, client: TestClient):
        pid = _project(client)
        m1 = _mem(client, pid, title="M1", content="Short content test.")
        m2 = _mem(client, pid, title="M2 which is a longer title for testing quality scores", content="A" * 250)
        expected_avg = round((m1["quality_score"] + m2["quality_score"]) / 2, 3)
        h = _health(client, pid)
        assert abs(h["avg_quality_score"] - expected_avg) < 0.005

    def test_superseded_memories_excluded_from_quality_avg(self, client: TestClient):
        pid = _project(client)
        m = _mem(client, pid, title="Original to supersede", content="Content to be superseded soon.")
        client.post(f"/memories/{m['id']}/supersede", json={
            "type": "decision",
            "title": "New superseding version of this memory",
            "content": "The replacement content for the superseded memory entry.",
        })
        h = _health(client, pid)
        # 1 active, 1 superseded — quality metrics should only cover the 1 active
        assert h["active_count"] == 1
        assert h["superseded_count"] == 1


# ---------------------------------------------------------------------------
# 5. Review status breakdown
# ---------------------------------------------------------------------------

class TestReviewBreakdown:
    def test_extracted_memory_counted_as_auto_extracted(self, client: TestClient):
        pid = _project(client)
        sid = _session(client, pid, "We decided to use FastAPI for the backend API.")
        client.post(f"/sessions/{sid}/extract-memories")
        h = _health(client, pid)
        assert h["review_breakdown"]["auto_extracted"] >= 1

    def test_verified_memory_counted_correctly(self, client: TestClient):
        pid = _project(client)
        sid = _session(client, pid, "We decided to use SQLite for local-first storage.")
        result = client.post(f"/sessions/{sid}/extract-memories").json()
        if result["memories"]:
            mem_id = result["memories"][0]["id"]
            client.put(f"/memories/{mem_id}", json={"review_status": "verified"})
        h = _health(client, pid)
        assert h["review_breakdown"]["verified"] >= 1

    def test_unset_review_status_counted_as_unset(self, client: TestClient):
        pid = _project(client)
        _mem(client, pid, title="No review status", content="Plain memory without review status set.")
        h = _health(client, pid)
        assert h["review_breakdown"]["unset"] >= 1


# ---------------------------------------------------------------------------
# 6. Traceability percentages
# ---------------------------------------------------------------------------

class TestTraceabilityMetrics:
    def test_pct_with_session_ref_correct(self, client: TestClient):
        pid = _project(client)
        # 1 with session ref (via extraction), 1 without
        sid = _session(client, pid, "We decided to use Docker for containerization.")
        client.post(f"/sessions/{sid}/extract-memories")
        _mem(client, pid, title="Manual memory no session", content="Memory without any session reference here.")

        h = _health(client, pid)
        total = h["total_memories"]
        # At least 1 has session ref (the extracted one)
        assert h["pct_with_session_ref"] > 0.0
        assert h["pct_with_session_ref"] <= 1.0

    def test_pct_with_source_type_correct(self, client: TestClient):
        pid = _project(client)
        _mem(client, pid, title="With source type", content="Memory with source type explicitly set.", source_type="manual")
        _mem(client, pid, title="Without source type", content="Memory without any source type information.")
        h = _health(client, pid)
        # 1 of 2 → 0.5
        assert abs(h["pct_with_source_type"] - 0.5) < 0.01

    def test_pct_with_source_quote_correct(self, client: TestClient):
        pid = _project(client)
        _mem(client, pid, title="With quote", content="Has a source quote attribute set.", source_quote="The original quote.")
        _mem(client, pid, title="Without quote", content="No source quote attribute on this one.")
        _mem(client, pid, title="No quote here", content="Another memory without source quote data.")
        h = _health(client, pid)
        assert abs(h["pct_with_source_quote"] - 1/3) < 0.02


# ---------------------------------------------------------------------------
# 7. Type distribution
# ---------------------------------------------------------------------------

class TestTypeDistribution:
    def test_type_distribution_counts_correctly(self, client: TestClient):
        pid = _project(client)
        _mem(client, pid, title="Decision 1", content="We decided to use X for Y.", mem_type="decision")
        _mem(client, pid, title="Decision 2", content="We decided to use A for B.", mem_type="decision")
        _mem(client, pid, title="Bug 1", content="There is a bug in the auth flow.", mem_type="problem")
        h = _health(client, pid)
        assert h["type_distribution"]["decision"] == 2
        assert h["type_distribution"]["problem"] == 1

    def test_type_distribution_only_active(self, client: TestClient):
        pid = _project(client)
        m = _mem(client, pid, title="Decision resolved", content="Resolved decision entry.", mem_type="decision")
        client.put(f"/memories/{m['id']}", json={"status": "resolved"})
        _mem(client, pid, title="Active task", content="Active task in the system.", mem_type="task")
        h = _health(client, pid)
        # "decision" was resolved → not in type_distribution
        assert h["type_distribution"].get("decision", 0) == 0
        assert h["type_distribution"].get("task", 0) == 1


# ---------------------------------------------------------------------------
# 8. Confidence metrics
# ---------------------------------------------------------------------------

class TestConfidenceMetrics:
    def test_avg_confidence_is_correct(self, client: TestClient):
        pid = _project(client)
        _mem(client, pid, title="High confidence", content="Very confident decision here.", confidence=1.0)
        _mem(client, pid, title="Low confidence", content="Uncertain decision, might change.", confidence=0.5)
        h = _health(client, pid)
        assert abs(h["avg_confidence"] - 0.75) < 0.01

    def test_low_confidence_count_correct(self, client: TestClient):
        pid = _project(client)
        _mem(client, pid, title="OK confidence", content="Memory with acceptable confidence level.", confidence=0.70)
        _mem(client, pid, title="Low confidence 1", content="First uncertain memory in this project.", confidence=0.50)
        _mem(client, pid, title="Low confidence 2", content="Second uncertain memory in this project.", confidence=0.40)
        h = _health(client, pid)
        assert h["low_confidence_count"] == 2  # both < 0.60


# ---------------------------------------------------------------------------
# 9–14. Issue detection
# ---------------------------------------------------------------------------

class TestIssueDetection:
    def test_high_unreviewed_triggers_warning(self, client: TestClient):
        pid = _project(client)
        # Create multiple auto-extracted memories (>50% of total)
        sid = _session(
            client, pid,
            "We decided to use FastAPI. We also decided to use SQLite. "
            "We must use Docker for deployment. This is a critical architecture decision."
        )
        client.post(f"/sessions/{sid}/extract-memories")
        h = _health(client, pid)
        codes = [i["code"] for i in h["issues"]]
        # If extraction produced >50% auto_extracted, this should fire
        if h["review_breakdown"]["auto_extracted"] > h["active_count"] // 2:
            assert "high_unreviewed_count" in codes

    def test_high_unreviewed_absent_when_majority_verified(self, client: TestClient):
        pid = _project(client)
        sid = _session(client, pid, "We decided to use FastAPI for the backend.")
        result = client.post(f"/sessions/{sid}/extract-memories").json()
        # Verify all extracted memories
        for m in result["memories"]:
            client.put(f"/memories/{m['id']}", json={"review_status": "verified"})
        h = _health(client, pid)
        codes = [i["code"] for i in h["issues"]]
        assert "high_unreviewed_count" not in codes

    def test_low_avg_quality_triggers_warning(self, client: TestClient):
        pid = _project(client)
        # Create minimal memories with very low quality scores
        for i in range(5):
            _mem(client, pid, title="X", content="Y" * 5)
        h = _health(client, pid)
        if h["avg_quality_score"] is not None and h["avg_quality_score"] < 0.40:
            codes = [i["code"] for i in h["issues"]]
            assert "low_avg_quality" in codes

    def test_rejected_memories_issue_fires(self, client: TestClient):
        pid = _project(client)
        sid = _session(client, pid, "We decided to use Redis for caching.")
        result = client.post(f"/sessions/{sid}/extract-memories").json()
        if result["memories"]:
            client.put(f"/memories/{result['memories'][0]['id']}", json={"review_status": "rejected"})
        h = _health(client, pid)
        codes = [i["code"] for i in h["issues"]]
        assert "rejected_memories_present" in codes

    def test_low_traceability_issue_fires(self, client: TestClient):
        pid = _project(client)
        # All memories with no source ref
        for i in range(5):
            _mem(client, pid,
                 title=f"Untraceable memory {i}",
                 content="Memory without any source traceability information.")
        h = _health(client, pid)
        codes = [i["code"] for i in h["issues"]]
        assert "low_traceability" in codes

    def test_low_traceability_absent_when_traced(self, client: TestClient):
        pid = _project(client)
        # All memories with source_type → traced
        for i in range(5):
            _mem(client, pid,
                 title=f"Traced memory {i}",
                 content="Memory with proper source attribution and traceability.",
                 source_type="manual")
        h = _health(client, pid)
        codes = [i["code"] for i in h["issues"]]
        assert "low_traceability" not in codes

    def test_issue_has_severity_and_message(self, client: TestClient):
        pid = _project(client)
        for i in range(4):
            _mem(client, pid, title="X", content="Y" * 5)
        h = _health(client, pid)
        for issue in h["issues"]:
            assert "severity" in issue
            assert "code" in issue
            assert "message" in issue
            assert issue["severity"] in ("warning", "info")


# ---------------------------------------------------------------------------
# 15. generated_at is ISO datetime
# ---------------------------------------------------------------------------

class TestReportMetadata:
    def test_generated_at_is_datetime(self, client: TestClient):
        pid = _project(client)
        h = _health(client, pid)
        assert "generated_at" in h
        # Should parse as a datetime without error
        dt = datetime.fromisoformat(h["generated_at"].replace("Z", "+00:00"))
        assert dt is not None

    def test_project_id_matches(self, client: TestClient):
        pid = _project(client)
        h = _health(client, pid)
        assert h["project_id"] == pid


# ---------------------------------------------------------------------------
# 16. 404 for unknown project
# ---------------------------------------------------------------------------

class TestHealthErrors:
    def test_404_for_unknown_project(self, client: TestClient):
        r = client.get("/projects/nonexistent-project-id/health")
        assert r.status_code == 404

    def test_health_and_memories_endpoint_independent(self, client: TestClient):
        pid = _project(client)
        _mem(client, pid, title="Independent test", content="Testing health and memories are independent.")
        h = _health(client, pid)
        r = client.get(f"/projects/{pid}/memories")
        assert r.status_code == 200
        assert h["active_count"] == len(r.json())
