#!/usr/bin/env python3
"""
Phase 3.2 — Build (query, fact, label) training pairs for cross-encoder fine-tuning.

Mines labeled pairs from all 3 benchmark datasets using cached facts + gold labels.
Hard negatives are generated by embedding each query with GTE-large and taking the
top-scoring non-gold facts — these are the realistic failure cases where the current
reranker needs to discriminate.

Output:
  training/reranker_train.jsonl   -- 80% split
  training/reranker_val.jsonl     -- 20% split

Stats per pair type:
  positive  -- fact from a gold session for this query  (label=1.0)
  hard_neg  -- top-ranked non-gold fact by GTE-large    (label=0.0)
  easy_neg  -- random non-gold fact from distant session (label=0.0)
"""
from __future__ import annotations

import json
import random
import sys
from pathlib import Path

import numpy as np

BENCH_DIR   = Path(__file__).resolve().parent.parent      # RetrievalEngine/
CACHE       = BENCH_DIR / "benchmark_cache"
TRAINING    = Path(__file__).resolve().parent
OUTPUT_TRAIN = TRAINING / "reranker_train.jsonl"
OUTPUT_VAL   = TRAINING / "reranker_val.jsonl"

DATASET_CONFIGS = [
    {
        "name":       "SQuAD v1.1",
        "cache_file": "squad.json",
        "facts_file": "facts_claude_SQuAD_v1.1.json",
        "emb_file":   "embed_facts_gte_large_SQuAD_v1.1.npy",
        "max_queries": 2500,         # increased from 800 — SQuAD needs more representation
    },
    {
        "name":       "LoCoMo",
        "cache_file": "locomo.json",
        "facts_file": "facts_claude_LoCoMo.json",
        "emb_file":   "embed_facts_gte_large_LoCoMo.npy",
        "max_queries": None,         # use all 690 LoCoMo queries
    },
    {
        "name":       "LongMemEval",
        "cache_file": "longmemeval.json",
        "facts_file": "facts_claude_LongMemEval.json",
        "emb_file":   "embed_facts_gte_large_LongMemEval.npy",
        "max_queries": None,         # use all 500 LME queries
    },
]

N_HARD_NEG = 5    # hard negatives per positive pair
N_EASY_NEG = 2    # easy negatives per positive pair
VAL_FRAC   = 0.20 # 80/20 train/val split
SEED       = 7    # different from benchmark seed=42


def load_gte_large():
    from sentence_transformers import SentenceTransformer
    print("Loading GTE-large for query embedding...")
    model = SentenceTransformer("thenlper/gte-large")
    print("  GTE-large ready")
    return model


def build_fact_rows(memories: list[dict], facts_by_session: dict[str, list[str]]) -> list[dict]:
    """
    Rebuild fact list in the exact same order used when building embed_facts_gte_large_*.npy.
    The benchmark iterates ds.memories in order and flattens facts per session.
    """
    rows: list[dict] = []
    for mem in memories:
        sid = mem["gold_key"]
        facts = facts_by_session.get(sid) or [mem["content"][:200]]
        for i, fact_text in enumerate(facts):
            rows.append({
                "idx":        len(rows),
                "fact":       fact_text,
                "session_id": sid,
            })
    return rows


def mine_dataset_pairs(
    ds_cfg: dict,
    model,
    rng: random.Random,
) -> list[dict]:
    ds_name    = ds_cfg["name"]
    cache_path = CACHE / ds_cfg["cache_file"]
    facts_path = CACHE / ds_cfg["facts_file"]
    emb_path   = CACHE / ds_cfg["emb_file"]

    print(f"\n── {ds_name} ──")

    # Load dataset cache (memories + all queries)
    raw = json.loads(cache_path.read_text())
    memories  = raw["memories"]
    all_queries = raw["queries"]

    # Optionally cap query count
    max_q = ds_cfg.get("max_queries")
    if max_q and len(all_queries) > max_q:
        all_queries = rng.sample(all_queries, max_q)
    print(f"  {len(memories):,} sessions · {len(all_queries):,} queries")

    # Load facts and embeddings
    facts_by_session: dict[str, list[str]] = json.loads(facts_path.read_text())
    fact_rows = build_fact_rows(memories, facts_by_session)
    fact_embs = np.load(str(emb_path)).astype(np.float32)
    assert fact_embs.shape[0] == len(fact_rows), (
        f"Embedding count {fact_embs.shape[0]} != fact count {len(fact_rows)}"
    )
    print(f"  {len(fact_rows):,} facts · embeddings {fact_embs.shape}")

    # Build session → fact indices map
    session_to_idxs: dict[str, list[int]] = {}
    for row in fact_rows:
        session_to_idxs.setdefault(row["session_id"], []).append(row["idx"])

    # Batch embed all queries with GTE-large
    query_texts = [q["question"] for q in all_queries]
    print(f"  Embedding {len(query_texts)} queries...")
    query_embs = model.encode(
        query_texts,
        batch_size=64,
        normalize_embeddings=True,
        show_progress_bar=True,
    ).astype(np.float32)

    all_idxs = list(range(len(fact_rows)))
    pairs: list[dict] = []

    for qi, qe in enumerate(all_queries):
        gold_sessions = set(qe["gold_keys"])

        # Collect gold fact indices
        gold_idxs: set[int] = set()
        for gs in gold_sessions:
            gold_idxs.update(session_to_idxs.get(gs, []))

        if not gold_idxs:
            continue

        nongold_idxs = [i for i in all_idxs if i not in gold_idxs]

        # ── Positives ──────────────────────────────────────────────────────────
        for idx in gold_idxs:
            pairs.append({
                "query":   qe["question"],
                "text":    fact_rows[idx]["fact"],
                "label":   1.0,
                "dataset": ds_name,
                "type":    "positive",
            })

        # ── Hard negatives: highest cosine non-gold facts ──────────────────────
        if nongold_idxs:
            qvec         = query_embs[qi]                       # (1024,) normalized
            nongold_embs = fact_embs[nongold_idxs]             # (M, 1024)
            sims         = nongold_embs @ qvec                  # cosine similarities
            top40        = np.argsort(sims)[::-1][:40].tolist()
            n_sample     = min(N_HARD_NEG, len(top40))
            hard_chosen  = rng.sample(top40[:20], n_sample)    # sample from top-20
            for j in hard_chosen:
                pairs.append({
                    "query":   qe["question"],
                    "text":    fact_rows[nongold_idxs[j]]["fact"],
                    "label":   0.0,
                    "dataset": ds_name,
                    "type":    "hard_neg",
                })

        # ── Easy negatives: random distant facts ────────────────────────────────
        if len(nongold_idxs) > 60:
            easy_pool   = nongold_idxs[:]
            easy_chosen = rng.sample(easy_pool, min(N_EASY_NEG, len(easy_pool)))
            for idx in easy_chosen:
                pairs.append({
                    "query":   qe["question"],
                    "text":    fact_rows[idx]["fact"],
                    "label":   0.0,
                    "dataset": ds_name,
                    "type":    "easy_neg",
                })

    pos  = sum(1 for p in pairs if p["type"] == "positive")
    hard = sum(1 for p in pairs if p["type"] == "hard_neg")
    easy = sum(1 for p in pairs if p["type"] == "easy_neg")
    print(f"  Pairs: {len(pairs):,} total  ({pos:,} pos · {hard:,} hard_neg · {easy:,} easy_neg)")
    return pairs


def main():
    rng = random.Random(SEED)
    model = load_gte_large()

    all_pairs: list[dict] = []
    for ds_cfg in DATASET_CONFIGS:
        pairs = mine_dataset_pairs(ds_cfg, model, rng)
        all_pairs.extend(pairs)

    # ── Global stats ────────────────────────────────────────────────────────────
    pos  = sum(1 for p in all_pairs if p["type"] == "positive")
    hard = sum(1 for p in all_pairs if p["type"] == "hard_neg")
    easy = sum(1 for p in all_pairs if p["type"] == "easy_neg")
    print(f"\nTotal: {len(all_pairs):,} pairs")
    print(f"  Positive:     {pos:,}  ({100*pos/len(all_pairs):.1f}%)")
    print(f"  Hard neg:     {hard:,}  ({100*hard/len(all_pairs):.1f}%)")
    print(f"  Easy neg:     {easy:,}  ({100*easy/len(all_pairs):.1f}%)")

    # ── Train/val split (stratified by dataset) ─────────────────────────────────
    rng.shuffle(all_pairs)
    val_size = int(len(all_pairs) * VAL_FRAC)
    val_pairs   = all_pairs[:val_size]
    train_pairs = all_pairs[val_size:]

    print(f"\nSplit: {len(train_pairs):,} train · {len(val_pairs):,} val")

    OUTPUT_TRAIN.write_text("\n".join(json.dumps(p) for p in train_pairs))
    OUTPUT_VAL.write_text("\n".join(json.dumps(p) for p in val_pairs))
    print(f"Saved: {OUTPUT_TRAIN}")
    print(f"Saved: {OUTPUT_VAL}")


if __name__ == "__main__":
    main()
