#!/usr/bin/env python3
"""
Phase 3.2 — Fine-tune cross-encoder reranker on X-MemoryArch training pairs.

Base model : cross-encoder/ms-marco-MiniLM-L-6-v2
Training   : reranker_train.jsonl  (generated by build_reranker_pairs.py)
Validation : reranker_val.jsonl
Output     : models/xma-reranker-v1/

The base model already knows retrieval relevance from MS MARCO. Fine-tuning on
mixed (SQuAD + LoCoMo + LME) pairs teaches it to handle both long passages and
12-17 word conversational atomic facts — fixing the LoCoMo domain gap.

Usage:
  cd RetrievalEngine/
  python3 training/finetune_reranker.py
  python3 training/finetune_reranker.py --epochs 3 --batch-size 16
"""
from __future__ import annotations

import argparse
import json
import random
import time
from pathlib import Path

parser = argparse.ArgumentParser()
parser.add_argument("--base-model",  default="cross-encoder/ms-marco-MiniLM-L-6-v2")
parser.add_argument("--epochs",      type=int,   default=5)
parser.add_argument("--batch-size",  type=int,   default=16)
parser.add_argument("--lr",          type=float, default=2e-5)
parser.add_argument("--warmup-frac", type=float, default=0.1,  help="fraction of steps for LR warmup")
parser.add_argument("--output",      default=None,             help="output path (default: models/xma-reranker-v1)")
parser.add_argument("--seed",        type=int,   default=42)
args = parser.parse_args()

random.seed(args.seed)

TRAINING  = Path(__file__).resolve().parent
BENCH_DIR = TRAINING.parent
MODELS    = BENCH_DIR / "models"
TRAIN_PATH = TRAINING / "reranker_train.jsonl"
VAL_PATH   = TRAINING / "reranker_val.jsonl"
OUTPUT_DIR = Path(args.output) if args.output else MODELS / "xma-reranker-v1"

# ── Validate inputs ────────────────────────────────────────────────────────────
if not TRAIN_PATH.exists():
    print(f"ERROR: {TRAIN_PATH} not found. Run build_reranker_pairs.py first.")
    raise SystemExit(1)
if not VAL_PATH.exists():
    print(f"ERROR: {VAL_PATH} not found. Run build_reranker_pairs.py first.")
    raise SystemExit(1)

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def load_jsonl(path: Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text().splitlines() if line.strip()]


def main():
    import torch
    from sentence_transformers.cross_encoder import CrossEncoder
    from sentence_transformers import InputExample
    from torch.utils.data import DataLoader

    # ── Device ────────────────────────────────────────────────────────────────
    if torch.backends.mps.is_available():
        device = "mps"
    elif torch.cuda.is_available():
        device = "cuda"
    else:
        device = "cpu"
    print(f"Device: {device}")

    # ── Load pairs ────────────────────────────────────────────────────────────
    train_raw = load_jsonl(TRAIN_PATH)
    val_raw   = load_jsonl(VAL_PATH)
    random.shuffle(train_raw)

    # Print dataset breakdown
    for split_name, raw in [("train", train_raw), ("val", val_raw)]:
        by_ds: dict[str, int] = {}
        for p in raw:
            by_ds[p["dataset"]] = by_ds.get(p["dataset"], 0) + 1
        breakdown = "  ".join(f"{k}={v}" for k, v in sorted(by_ds.items()))
        pos  = sum(1 for p in raw if p["type"] == "positive")
        neg  = len(raw) - pos
        print(f"{split_name}: {len(raw):,} pairs  pos={pos:,} neg={neg:,}  |  {breakdown}")

    # ── Build InputExamples ───────────────────────────────────────────────────
    train_examples = [
        InputExample(texts=[p["query"], p["text"]], label=float(p["label"]))
        for p in train_raw
    ]
    val_examples = [
        InputExample(texts=[p["query"], p["text"]], label=float(p["label"]))
        for p in val_raw
    ]

    train_dataloader = DataLoader(train_examples, shuffle=True, batch_size=args.batch_size)
    steps_per_epoch  = len(train_dataloader)
    total_steps      = steps_per_epoch * args.epochs
    warmup_steps     = int(total_steps * args.warmup_frac)

    print(f"\nBase model : {args.base_model}")
    print(f"Epochs     : {args.epochs}  |  Batch: {args.batch_size}  |  LR: {args.lr}")
    print(f"Steps      : {total_steps:,} total  |  {steps_per_epoch:,}/epoch  |  warmup: {warmup_steps:,}")
    print(f"Output     : {OUTPUT_DIR}\n")

    # ── Load model ────────────────────────────────────────────────────────────
    model = CrossEncoder(args.base_model, num_labels=1, device=device)

    # ── Validation evaluator (ranking MRR on query→facts) ─────────────────────
    from sentence_transformers.cross_encoder.evaluation import CrossEncoderRerankingEvaluator

    val_by_query: dict[str, dict] = {}
    for p in val_raw:
        q = p["query"]
        if q not in val_by_query:
            val_by_query[q] = {"query": q, "positive": [], "negative": []}
        if p["label"] == 1.0:
            val_by_query[q]["positive"].append(p["text"])
        else:
            val_by_query[q]["negative"].append(p["text"])

    val_samples = [
        v for v in val_by_query.values()
        if v["positive"] and v["negative"]
    ]
    print(f"Validation samples: {len(val_samples):,} queries with pos+neg pairs")
    evaluator = CrossEncoderRerankingEvaluator(val_samples, name="val")

    # ── Fine-tune ─────────────────────────────────────────────────────────────
    # evaluation_steps=steps_per_epoch → evaluator fires at end of each epoch
    # This enables save_best_model to track improvements and save checkpoints
    t0 = time.monotonic()
    model.fit(
        train_dataloader=train_dataloader,
        evaluator=evaluator,
        epochs=args.epochs,
        warmup_steps=warmup_steps,
        evaluation_steps=steps_per_epoch,   # evaluate once per epoch
        output_path=str(OUTPUT_DIR),
        optimizer_params={"lr": args.lr},
        show_progress_bar=True,
        save_best_model=True,
    )
    elapsed = time.monotonic() - t0
    print(f"\nFine-tuning done in {elapsed/60:.1f} min")

    # Always save final model — backup for when save_best_model conditions aren't met
    model.save(str(OUTPUT_DIR / "final"))
    print(f"Final model saved to: {OUTPUT_DIR / 'final'}")

    # ── Final validation score ─────────────────────────────────────────────────
    print("\nFinal validation scores:")
    scores = evaluator(model, output_path=str(OUTPUT_DIR))
    if isinstance(scores, dict):
        for k, v in scores.items():
            print(f"  {k}: {v:.4f}")
    else:
        print(f"  score: {scores:.4f}")
    print(f"\nTo benchmark: python3 benchmark_4approaches.py --skip-ollama --skip-cloud --reranker-model {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
